### ISSUE TITLE
De-serializing request with multiple data objects

### ISSUE THREAD

**Issue by noordawod** [RestExpress/RestExpress#119]
Hi again.

Normally, a client request which arrives to the server in the form:

```
{
  "name": "User name",
  "email": "user@example.com",
  ...
}
```

is easy to deserialize using `request.getBodyAs(User.class)` to auto-fill the `User` instance.

However, in my program, there's a need to send multiple objects from client to the server, each one having its own property name in JSON. As an example:

```
{
  "user": { <user details here> },
  "device": { <device details here> },
  "session": { <session details here> }
}
```

Each top-level property holds details about that property (so, if each were to be sent on its own as a JSON object, then `request.getBodyAs()` would suffice to get the details.)

How do I go around to deserializing the whole request as 3 distinct instances of different types. I envision something like the following would be needed:

```
  User user = request.getPropertyBodyAs(User.class, "user");
  Device device = request.getPropertyBodyAs(Device.class, "device");
  Session session = request.getPropertyBodyAs(Session.class, "session");
```

But, alas, I don't have this facilitated in the current code.

Could you think of an alternative?

**Comment by tfredrich** [comment]
Perhaps something along the lines of a first-class object that has properties of user, device, session, with each of them typed. A class like this might work:

public class AllMyStuff {
    private User user;
    private Device device;
    private Session session:
}

**Comment by noordawod** [comment]
@tfredrich great minds think alike :) that's exactly what I ended up doing, although I forgot that I created an issue for it.
