### ISSUE TITLE
HI，I want to know how to implement file upload and download flow high effectly，such as image file upload and download. can you show us a demo ? thanks

### ISSUE THREAD

**Issue by longzhou3** [RestExpress/RestExpress#121]

**Comment by tfredrich** [comment]
RestExpress was designed for JSON-based RESTful services and as such doesn't do binary image uploads/downloads with "high efficiency" as you request. There is a discussion about how-to do the download portion here: https://groups.google.com/forum/#!topic/restexpress/Q1eSb31-l0w

For the upload part, you'd want to get the body as an InputStream and write it to a file or db. The method on the request is: Request.getBodyAsStream() to do that. Or you could use Request.getBody() which returns a ByteBuf and you can have your way with it.

**Comment by tfredrich** [comment]
BTW, the way RestExpress configures Netty, the entire image must be uploaded before it sends that request to your controller--works fine for JSON, not so much for images. Same for the download process, currently--the entire image resides in memory before being streamed down to the client--again, fine for JSON payloads, not so much for giant images.
