### ISSUE TITLE
Compression should be configureable

### ISSUE THREAD

**Issue by shawn11ZX** [RestExpress/RestExpress#126]
We have a HTTP sever receiving simple GET request and then responding very short string (less than 5 character).
At peak hours, QPS will arrive as high as 10000.
At first we observed that the performance of RestExpress is far more worse than pure netty (CPU utilization at least doubled).
After some experience, we found that if Compression(HttpContentCompressor) is disabled (since our response is short we didn't need it anyway), performance is much better.

**Comment by tfredrich** [comment]
Very interesting! Thanks for the feedback. I'll put it on the backlog.

**Comment by tfredrich** [comment]
Available in 0.11.4-SNAPSHOT via server.noCompression()

**Comment by shawn11ZX** [comment]
excellent, thanks!

**Comment by noordawod** [comment]
Actually, this could be a nice feature on a per-request basis. For example, URI's pulling password-protected binary downloads do not need compression when sending the data back to the client.
