### ISSUE TITLE
JacksonDatabind version

### ISSUE THREAD

**Issue by vlad4800** [RestExpress/RestExpress#127]
In Release 0.11.3 you upgraded it to 2.6.0. Why not upgrade it to: 2.7.1-1 (03-Feb-2016)?

**Comment by petromir** [comment]
Probably, because 2.7.1-1 is a bit buggy. I expect that they will switch directly to 2.8

**Comment by tfredrich** [comment]
2.7.4 is available in 0.11.4-SNAPSHOT
