### ISSUE TITLE
How do I handle file uploads?

### ISSUE THREAD

**Issue by mohsalsaleem** [RestExpress/RestExpress#145]
I'm sending a file from browser in the input tag 
`<input type="file" name="test" />`

I used the following to get the object. But it returns null.
`request.getAttachement("test')`

Any help is appreciated.
TIA

**Comment by tfredrich** [comment]
As of 0.12.0-SNAPSHOT large, multi-part file uploads are supported but must be enabled by calling supportFileUploads() on the RestExpress server instance.

In the controller:

File f = request.getUploadedFileAttachment();

will return a handle to the temporary file that was uploaded.
