### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by noordawod** [RestExpress/RestExpress#149]
With Java 11, all Java EE technologies were removed, so RestExpress will fail to compile.

There are two fixes for this:

1) using an alternative versions of Java EE as described here: https://stackoverflow.com/a/52502208
2) refactor RestExpress to use alternative functions with the same functionality.

What do you say, @tfredrich?

**Comment by tfredrich** [comment]
Version 0.12.0-SNAPSHOT now compiles with Java 11.
